"""oauth account

Revision ID: 92e0bece0dd9
Revises: 9a71074344e9
Create Date: 2024-06-16 00:57:02.607296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e0bece0dd9'
down_revision: Union[str, None] = '9a71074344e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор OAuth aккаунта пользователя'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Идентификатор пользователя, связанного с OAuth аккаунтом'),
    sa.Column('oauth_user_id', sa.String(length=255), nullable=False, comment='Идентификатор пользователя у провайдера OAuth'),
    sa.Column('oauth_provider_name', sa.String(length=255), nullable=False, comment='Название провайдера OAuth'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('oauth_user_id', 'oauth_provider_name', name='oauth_acc')
    )
    op.create_unique_constraint(None, 'roles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_table('oauth_account')
    # ### end Alembic commands ###
